version: "2"
services:
  web:
    build: .
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app
    ports:
      - "3002:3000"
  mongo:
    image: mongo
    ports:
      - "27018:27017"